ALTER TABLE users
  ADD COLUMN IF NOT EXISTS agreed_to_tos BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS agreed_to_privacy BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users
ADD COLUMN IF NOT EXISTS agreed_to_tos BOOLEAN NOT NULL DEFAULT FALSE;

